// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4chZYZ9EGU7d28k-OaJ6EX_l7H3QHx4Y',
    appId: '1:228825937936:web:b6fb7af86ce191b7db3295',
    messagingSenderId: '228825937936',
    projectId: 'tripaiuz',
    authDomain: 'tripaiuz.firebaseapp.com',
    storageBucket: 'tripaiuz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUQobhRh8A9fWe6a4uPPlsalfTYq1Eaw',
    appId: '1:228825937936:android:bef5a06ae6dacc99db3295',
    messagingSenderId: '228825937936',
    projectId: 'tripaiuz',
    storageBucket: 'tripaiuz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDlmwHn65mRbHxjZ6lKVLqj1J5SanIw_s',
    appId: '1:228825937936:ios:dda1cff548601e8ddb3295',
    messagingSenderId: '228825937936',
    projectId: 'tripaiuz',
    storageBucket: 'tripaiuz.appspot.com',
    iosClientId: '228825937936-h593s54h22h8tt364798kqfqm33pador.apps.googleusercontent.com',
    iosBundleId: 'uz.thelab.tripai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDlmwHn65mRbHxjZ6lKVLqj1J5SanIw_s',
    appId: '1:228825937936:ios:dda1cff548601e8ddb3295',
    messagingSenderId: '228825937936',
    projectId: 'tripaiuz',
    storageBucket: 'tripaiuz.appspot.com',
    iosClientId: '228825937936-h593s54h22h8tt364798kqfqm33pador.apps.googleusercontent.com',
    iosBundleId: 'uz.thelab.tripai',
  );
}
